/* Rural Connect multilingual UI. English, Marathi and Hindi. */
const RC_TRANSLATIONS={
  en:{home:'Home',about:'About',schemes:'Schemes',agriculture:'Agriculture',weather:'Weather',market:'Market',opportunities:'Opportunities',login:'Login',register:'Register',dashboard:'Dashboard',profile:'Profile',logout:'Logout',language:'Language',chatTitle:'Rural Connect AI',chatPlaceholder:'Ask about schemes, farming, complaints...',chatWelcome:'Hello! I can help with schemes, agriculture, market information and Rural Connect services.',chatSend:'Send',chatThinking:'Thinking...',chatError:'I could not connect to the chatbot. Please make sure the Rural Connect backend is running.',report:'Report a Problem',findSchemes:'Find Schemes',checkWeather:'Check Weather',agriInfo:'Agriculture Info',emergency:'Emergency Alerts',governmentSchemes:'Government Schemes',viewAllSchemes:'View All Schemes',announcements:'Village Announcements',searchSchemes:'Search schemes...',reportHint:'Raise and track local issues',schemeHint:'Discover useful public schemes',agriHint:'Practical farming information',weatherHint:'Check local weather updates',marketHint:'View market-price information',opportunityHint:'Find work and growth opportunities',fleetManagement:'Fleet Management',vehicles:'Vehicles',drivers:'Drivers',trips:'Trips',maintenance:'Maintenance',fuel:'Fuel Records',totalVehicles:'Total Vehicles',availableVehicles:'Available Vehicles',onTripVehicles:'On Trip',maintenanceVehicles:'Maintenance',activeDrivers:'Active Drivers',activeTrips:'Active Trips',addVehicle:'Add Vehicle',editVehicle:'Edit Vehicle',deleteVehicle:'Delete Vehicle',vehicleNumber:'Vehicle Number',vehicleType:'Vehicle Type',vehicleModel:'Vehicle Model',driver:'Driver',status:'Status',location:'Location',save:'Save',cancel:'Cancel',noVehicles:'No vehicles found.',bookVehicle:'Book Vehicle',bookableVehicles:'Vehicles Available for Booking',bookVehicleHint:'Choose an available vehicle and submit your booking request.',bookNow:'Book Now',bookingDate:'Booking Date',bookingTime:'Preferred Time',bookingPurpose:'Purpose',bookingNotes:'Additional Notes',submitBooking:'Submit Booking',myBookings:'My Bookings',pending:'Pending',approved:'Approved',rejected:'Rejected',completed:'Completed',booked:'Booked',bookingSubmitted:'Booking submitted successfully.',noBookings:'No bookings yet.',bookingStatus:'Booking Status',manageBookings:'Manage Bookings',approve:'Approve',reject:'Reject',markCompleted:'Mark Completed',fleet:'Fleet',viewFleet:'View Vehicles',bookVehicleLogin:'Please log in to book a vehicle.'},
  mr:{home:'मुख्यपृष्ठ',about:'आमच्याबद्दल',schemes:'शासकीय योजना',agriculture:'शेती',weather:'हवामान',market:'बाजारभाव',opportunities:'संधी',login:'लॉगिन',register:'नोंदणी',dashboard:'डॅशबोर्ड',profile:'प्रोफाइल',logout:'बाहेर पडा',language:'भाषा',chatTitle:'Rural Connect AI',chatPlaceholder:'योजना, शेती, तक्रारींबद्दल विचारा...',chatWelcome:'नमस्कार! मी योजना, शेती, बाजारभाव आणि Rural Connect सेवांबद्दल मदत करू शकतो.',chatSend:'पाठवा',chatThinking:'विचार करत आहे...',chatError:'चॅटबॉटशी जोडता आले नाही. Rural Connect backend सुरू आहे याची खात्री करा.',report:'समस्या नोंदवा',findSchemes:'योजना शोधा',checkWeather:'हवामान तपासा',agriInfo:'शेती माहिती',emergency:'आपत्कालीन सूचना',governmentSchemes:'शासकीय योजना',viewAllSchemes:'सर्व योजना पहा',announcements:'गावातील घोषणा',searchSchemes:'योजना शोधा...',reportHint:'स्थानिक समस्या नोंदवा आणि त्यांचा मागोवा घ्या',schemeHint:'उपयुक्त शासकीय योजना शोधा',agriHint:'शेतीविषयक उपयुक्त माहिती',weatherHint:'स्थानिक हवामान अपडेट तपासा',marketHint:'बाजारभावाची माहिती पहा',opportunityHint:'काम आणि प्रगतीच्या संधी शोधा',fleetManagement:'वाहन व्यवस्थापन',vehicles:'वाहने',drivers:'चालक',trips:'फेऱ्या',maintenance:'देखभाल',fuel:'इंधन नोंदी',totalVehicles:'एकूण वाहने',availableVehicles:'उपलब्ध वाहने',onTripVehicles:'फेरीवर',maintenanceVehicles:'देखभालीत',activeDrivers:'सक्रिय चालक',activeTrips:'सक्रिय फेऱ्या',addVehicle:'वाहन जोडा',editVehicle:'वाहन संपादित करा',deleteVehicle:'वाहन हटवा',vehicleNumber:'वाहन क्रमांक',vehicleType:'वाहन प्रकार',vehicleModel:'वाहन मॉडेल',driver:'चालक',status:'स्थिती',location:'स्थान',save:'जतन करा',cancel:'रद्द करा',noVehicles:'कोणतीही वाहने सापडली नाहीत.',bookVehicle:'वाहन बुक करा',bookableVehicles:'बुकिंगसाठी उपलब्ध वाहने',bookVehicleHint:'उपलब्ध वाहन निवडा आणि बुकिंग विनंती पाठवा.',bookNow:'आता बुक करा',bookingDate:'बुकिंग दिनांक',bookingTime:'पसंतीची वेळ',bookingPurpose:'उद्देश',bookingNotes:'अतिरिक्त नोंदी',submitBooking:'बुकिंग पाठवा',myBookings:'माझी बुकिंग',pending:'प्रलंबित',approved:'मंजूर',rejected:'नाकारले',completed:'पूर्ण',booked:'बुक केलेले',bookingSubmitted:'बुकिंग यशस्वीरीत्या पाठवले.',noBookings:'अजून कोणतीही बुकिंग नाही.',bookingStatus:'बुकिंग स्थिती',manageBookings:'बुकिंग व्यवस्थापन',approve:'मंजूर करा',reject:'नकार द्या',markCompleted:'पूर्ण म्हणून चिन्हांकित करा',fleet:'वाहन व्यवस्था',viewFleet:'वाहने पहा',bookVehicleLogin:'वाहन बुक करण्यासाठी कृपया लॉगिन करा.'},
  hi:{home:'होम',about:'हमारे बारे में',schemes:'सरकारी योजनाएँ',agriculture:'कृषि',weather:'मौसम',market:'बाजार भाव',opportunities:'अवसर',login:'लॉगिन',register:'पंजीकरण',dashboard:'डैशबोर्ड',profile:'प्रोफ़ाइल',logout:'लॉगआउट',language:'भाषा',chatTitle:'Rural Connect AI',chatPlaceholder:'योजना, खेती, शिकायतों के बारे में पूछें...',chatWelcome:'नमस्ते! मैं योजनाओं, कृषि, बाजार जानकारी और Rural Connect सेवाओं में मदद कर सकता हूँ।',chatSend:'भेजें',chatThinking:'सोच रहा हूँ...',chatError:'चैटबॉट से कनेक्ट नहीं हो पाया। कृपया Rural Connect backend शुरू करें।',report:'समस्या दर्ज करें',findSchemes:'योजनाएँ खोजें',checkWeather:'मौसम देखें',agriInfo:'कृषि जानकारी',emergency:'आपातकालीन सूचनाएँ',governmentSchemes:'सरकारी योजनाएँ',viewAllSchemes:'सभी योजनाएँ देखें',announcements:'गाँव की घोषणाएँ',searchSchemes:'योजनाएँ खोजें...',reportHint:'स्थानीय समस्याएँ दर्ज करें और ट्रैक करें',schemeHint:'उपयोगी सरकारी योजनाएँ खोजें',agriHint:'खेती से जुड़ी उपयोगी जानकारी',weatherHint:'स्थानीय मौसम अपडेट देखें',marketHint:'बाजार भाव की जानकारी देखें',opportunityHint:'काम और विकास के अवसर खोजें',fleetManagement:'वाहन प्रबंधन',vehicles:'वाहन',drivers:'चालक',trips:'यात्राएँ',maintenance:'रखरखाव',fuel:'ईंधन रिकॉर्ड',totalVehicles:'कुल वाहन',availableVehicles:'उपलब्ध वाहन',onTripVehicles:'यात्रा पर',maintenanceVehicles:'रखरखाव में',activeDrivers:'सक्रिय चालक',activeTrips:'सक्रिय यात्राएँ',addVehicle:'वाहन जोड़ें',editVehicle:'वाहन संपादित करें',deleteVehicle:'वाहन हटाएँ',vehicleNumber:'वाहन नंबर',vehicleType:'वाहन प्रकार',vehicleModel:'वाहन मॉडल',driver:'चालक',status:'स्थिति',location:'स्थान',save:'सहेजें',cancel:'रद्द करें',noVehicles:'कोई वाहन नहीं मिला।',bookVehicle:'वाहन बुक करें',bookableVehicles:'बुकिंग के लिए उपलब्ध वाहन',bookVehicleHint:'उपलब्ध वाहन चुनें और अपनी बुकिंग अनुरोध भेजें।',bookNow:'अभी बुक करें',bookingDate:'बुकिंग तारीख',bookingTime:'पसंदीदा समय',bookingPurpose:'उद्देश्य',bookingNotes:'अतिरिक्त जानकारी',submitBooking:'बुकिंग भेजें',myBookings:'मेरी बुकिंग',pending:'लंबित',approved:'स्वीकृत',rejected:'अस्वीकृत',completed:'पूर्ण',booked:'बुक किया गया',bookingSubmitted:'बुकिंग सफलतापूर्वक भेज दी गई।',noBookings:'अभी कोई बुकिंग नहीं है।',bookingStatus:'बुकिंग स्थिति',manageBookings:'बुकिंग प्रबंधन',approve:'स्वीकृत करें',reject:'अस्वीकृत करें',markCompleted:'पूर्ण चिह्नित करें',fleet:'वाहन व्यवस्था',viewFleet:'वाहन देखें',bookVehicleLogin:'वाहन बुक करने के लिए कृपया लॉगिन करें.'}
};
function rcGetLanguage(){return localStorage.getItem('rc_language')||'en';}
function rcSetLanguage(lang){if(!RC_TRANSLATIONS[lang])lang='en';localStorage.setItem('rc_language',lang);document.documentElement.lang=lang==='mr'?'mr':lang;document.dispatchEvent(new CustomEvent('rc-language-changed',{detail:lang}));}
function rcT(key){return (RC_TRANSLATIONS[rcGetLanguage()]||RC_TRANSLATIONS.en)[key]||RC_TRANSLATIONS.en[key]||key;}
function rcApplyCommonTranslations(){
  document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(RC_TRANSLATIONS[rcGetLanguage()][key])el.textContent=rcT(key);});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=rcT(el.dataset.i18nPlaceholder));
  const sel=document.querySelector('#rc-language-select'); if(sel) sel.value=rcGetLanguage();
  const title=document.querySelector('[data-i18n-title]'); if(title) document.title=rcT(title.dataset.i18nTitle);
}
function rcInitLanguage(){
  let wrap=document.getElementById('rc-language-control');
  if(!wrap){wrap=document.createElement('div');wrap.id='rc-language-control';wrap.className='rc-language-control';wrap.innerHTML=`<label for="rc-language-select">${rcT('language')}</label><select id="rc-language-select" aria-label="${rcT('language')}"><option value="en">English</option><option value="mr">मराठी</option><option value="hi">हिंदी</option></select>`;document.body.appendChild(wrap);}
  const sel=wrap.querySelector('select'); sel.value=rcGetLanguage(); sel.onchange=()=>rcSetLanguage(sel.value); rcApplyCommonTranslations();
}
document.addEventListener('DOMContentLoaded',rcInitLanguage);document.addEventListener('rc-language-changed',rcApplyCommonTranslations);
